apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apache
  namespace: honey
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache

    spec:
      containers:
      - name: apache
        image: honeyreddy/static-website/apache:6
        ports:
        - containerPort: 80
